version: '2'
services:
  server:
    image: ncubeschool/web-server
    ports:
     - "7070:80"
    volumes:
     - ./src:/var/www/edu
    depends_on:
     - ncube-db
     - phpmyadmin
    container_name: web-server
  ncube-db:
    image: mysql
    container_name: ncube-db
    ports:
     - "7072:3306"
    environment:
     MYSQL_ROOT_PASSWORD: p@55w@rD
    volumes:
     - ./db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
     - "7073:80"
    environment:
     PMA_HOST: ncube-db