-- MySQL Script generated by MySQL Workbench
-- Wednesday 08 February 2017 12:24:17 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema edu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema edu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edu` DEFAULT CHARACTER SET utf8 ;
USE `edu` ;

-- -----------------------------------------------------
-- Table `edu`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`user` (
  `user_id` VARCHAR(32) NOT NULL,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `gender` VARCHAR(6) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `country` VARCHAR(5) NULL DEFAULT NULL,
  `profile_pic` VARCHAR(32) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '0',
  `public` TINYINT(1) NOT NULL DEFAULT '1',
  `last_login` BIGINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edu`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`question` (
  `q_id` VARCHAR(32) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `title` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `views` INT(11) NOT NULL,
  `public` TINYINT(1) NULL DEFAULT '0',
  `status` TINYINT(1) NULL DEFAULT '0',
  `time` BIGINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`q_id`, `user_id`),
  INDEX `fk_questions_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_questions_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edu`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`answer` (
  `a_id` INT(11) NOT NULL AUTO_INCREMENT,
  `q_id` VARCHAR(32) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '0',
  `time` BIGINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`a_id`, `q_id`, `user_id`),
  INDEX `fk_answer_user1_idx` (`user_id` ASC),
  INDEX `fk_answer_question1_idx` (`q_id` ASC),
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`q_id`)
    REFERENCES `edu`.`question` (`q_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edu`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`follow` (
  `follow_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(32) NOT NULL,
  `following_id` VARCHAR(32) NOT NULL,
  `time` BIGINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`follow_id`, `user_id`, `following_id`),
  INDEX `fk_follow_users_idx` (`user_id` ASC),
  INDEX `fk_follow_users1_idx` (`following_id` ASC),
  CONSTRAINT `fk_follow_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follow_users1`
    FOREIGN KEY (`following_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edu`.`msg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`msg` (
  `msg_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `from_id` VARCHAR(32) NOT NULL,
  `to_id` VARCHAR(32) NOT NULL,
  `msg` VARCHAR(1000) NOT NULL,
  `time` BIGINT(10) NULL DEFAULT NULL,
  `status` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`msg_id`, `from_id`, `to_id`),
  INDEX `fk_msg_users1_idx` (`from_id` ASC),
  INDEX `fk_msg_users2_idx` (`to_id` ASC),
  CONSTRAINT `fk_msg_users1`
    FOREIGN KEY (`from_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_msg_users2`
    FOREIGN KEY (`to_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 106
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edu`.`msg_notif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`msg_notif` (
  `notif_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(32) NOT NULL,
  `to_id` VARCHAR(32) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '0',
  `time` BIGINT(10) NOT NULL,
  PRIMARY KEY (`notif_id`, `user_id`, `to_id`),
  INDEX `fk_msg_notif_user1_idx` (`user_id` ASC),
  INDEX `fk_msg_notif_user2_idx` (`to_id` ASC),
  CONSTRAINT `fk_msg_notif_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_msg_notif_user2`
    FOREIGN KEY (`to_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edu`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`notification` (
  `notif_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(32) NOT NULL,
  `to_id` VARCHAR(32) NOT NULL,
  `type` VARCHAR(2) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '0',
  `time` BIGINT(10) NOT NULL,
  PRIMARY KEY (`notif_id`, `user_id`, `to_id`),
  INDEX `fk_notification_user2_idx` (`to_id` ASC),
  INDEX `fk_notification_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_notification_user2`
    FOREIGN KEY (`to_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edu`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`post` (
  `post_id` INT(11) NOT NULL AUTO_INCREMENT,
  `unique_id` VARCHAR(32) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `post_data` VARCHAR(1000) NULL DEFAULT NULL,
  `status` INT(11) NOT NULL DEFAULT '0',
  `time` BIGINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`, `user_id`),
  INDEX `fk_post_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edu`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`vote` (
  `vote_id` INT(11) NOT NULL AUTO_INCREMENT,
  `q_id` VARCHAR(32) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `vote` TINYINT(1) NULL DEFAULT NULL,
  `time` BIGINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`vote_id`, `q_id`, `user_id`),
  INDEX `fk_vote_user1_idx` (`user_id` ASC),
  INDEX `fk_vote_question1_idx` (`q_id` ASC),
  CONSTRAINT `fk_vote_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_question1`
    FOREIGN KEY (`q_id`)
    REFERENCES `edu`.`question` (`q_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edu`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`groups` (
  `group_id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(250) NULL,
  `parent` VARCHAR(32) NULL,
  `time` BIGINT(10) NULL,
  `public` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edu`.`groups_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edu`.`groups_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` VARCHAR(32) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `status` FLOAT NOT NULL DEFAULT 0,
  `type` VARCHAR(3) NOT NULL,
  `time` BIGINT(10) NULL,
  PRIMARY KEY (`id`, `group_id`, `user_id`),
  INDEX `fk_groups_users_groups1_idx` (`group_id` ASC),
  INDEX `fk_groups_users_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_groups_users_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `edu`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_users_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edu`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
